name: Makefile CI

on:
  push:
    branches: [ "playground" ]
  pull_request:
    branches: [ "playground" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/arm64
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Go 1.23.2
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
        platforms: '{{ matrix.platform }}'
    - name: Run debug
      run: arch
      with:
        platforms: 'linux/arm64'

    - name: create tarball
      run: make common-tarball
      with:
        platforms: 'linux/arm64'
