name: Makefile CI

on:
  push:
    branches: [ "playground" ]
  pull_request:
    branches: [ "playground" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go 1.23.2
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
    - name: Run style check
      run: make common-style
    - name: Run build
      run: make common-build
    - name: create tarball
      run: make common-tarball
