name: Makefile CI

on:
  push:
    branches: [ "playground" ]
  pull_request:
    branches: [ "playground" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/arm64
          - linux/amd64
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set cache name
      id: cache-name
      run: |
        echo 'cache-name=asterisk-cache-${{ matrix.platform }}' | sed 's:/:-:g' >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: false
        tags: nodebuild:notused
        platforms: "${{ matrix.platform }}"
        cache-from: type=gha

    - name: extract binaries
      uses: addnab/docker-run-action@v3
      with:
        image: nodebuild:notused
        options: "-v ${{ github.workspace }}:/host"
        run: "cp /build/*.tar.* /host"
    - name: check tar exists
      run: "ls *.tar.*"
