name: Makefile CI

on:
  push:
    branches: [ "playground" ]
  pull_request:
    branches: [ "playground" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/arm64
          - linux/x86_64
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: false
        tags: nodebuild:notused
        platform: "{{ matrix.platform }}"
    - name: extract binaries
      uses: addnab/docker-run-action@v3
      with:
        image: nodebuild:notused
        options: "-v ${{ github.workspace }}:/host"
        run: "cp /build/*.tar.* /host"
    - name: check tar exists
      run: "ls *.tar.*"
