on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.23.2
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      - name: Run style check
        run: make common-style
      - name: Run build
        run: make common-build
      - name: create tarball
        run: make common-tarball
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.tar.*'
